### ISSUE TITLE
Use $PROJECT_NAME variable in Executable Path option

### ISSUE THREAD

**Issue by tebanep** [elarivie/linter-mypy#2]
I think the option to use a **$PROJECT_NAME** variable in the **Executable Path** option will be very useful to have a single configuration that can work with multiple virtual environments (for example those created with the **virtualenvwrapper** tool that are installed in the **~/.virtualenvs** directory and that have by convention the same name of the project that uses it)

This would be similar to the **Python Executable Paths** of package **autocomplete-python**

`/home/user/.virtualenvs/$PROJECT_NAME/bin/python`

Thank you!

**Comment by elarivie** [comment]
Thanks for the implementation of @tebanep and the review of @Arcanemagus

This issue has been resolved with pull request #3
