### ISSUE TITLE
Read settings from setup.cfg

### ISSUE THREAD

**Issue by andrew-ang** [elarivie/linter-mypy#21]
I understand that `linter-mypy` is able to read configs from `mypy.ini`, but is it able to read from `setup.cfg`?

**Comment by elarivie** [comment]
Hello @andrew-ang 

Yes this is already supported.

Actually linter-mypy does not actually read configs file, it merely validate its presence.

At lint time:

1.  [see in code](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L469)   linter-mypy check If the configuration file path provided in the setting "Mypy Ini file" actually exists
 
2. [see in code](https://github.com/elarivie/linter-mypy/blob/master/lib/init.coffee#L471) If it does, linter-mypy provides its path to mypy using the option [--config-file](https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-config-file) which as the doc says, it handles both format.


Effectively the linter-mypy setting currently name "**Mypy Ini file**" should probably be rename to something more generic like "**Mypy config file**"

**Comment by elarivie** [comment]
Hello @andrew-ang 

FYI:  I just did a new linter-mypy release (v2.6.7) which rename the setting "Mypy Ini file" -> "Mypy Config file""
