### ISSUE TITLE
(semi-) colon separated Python Executable Path?

### ISSUE THREAD

**Issue by keisuke-nakata** [elarivie/linter-mypy#26]
Linter-mypy works great for my work, but I have a small issue.

The `Python Executable Path` setting does not allow multiple paths.  
I'd like to set "Use project-specific python if available, otherwise fallback to default python", but current linter-mypy does not seem to allow this.

**Comment by elarivie** [comment]
Hello @keisuke-nakata 
1. Your request is highly similar to this other request: https://github.com/elarivie/atom-python-linters/issues/6#issuecomment-673017488

The solution is to create a python wrapper script which embed the logic for your specific use case.

2. When editing the linter-mypy settings for the Python Executable Path you have the possibility to use the variables ```$PROJECT_PATH``` and ```$PROJECT_NAME```
 so you can specify different executable per project using those

Using the above two points you can adapt python calls to your specific use case 

Note: linter-mypy does not have the concept of default python but this could be a logic that you implement in a python wrapper script.

Let me know if it solves your issue

**Comment by keisuke-nakata** [comment]
@elarivie 
Great! It looks pretty smart, however, on my Atom, `$PROJECT_NAME` was not available in the wrapper script.
It seems that the `$PROJECT_NAME` is only used for resolving `Python Executable Path` itself and not passed into the `Python Executable`.

**Comment by keisuke-nakata** [comment]
I tried setting `PROJECT_NAME=$PROJECT_NAME /some/path/to/pythonwrapper.sh` as `Python Executable Path`, but it didn't work. (linter-mypy regards it as a command containing a space)

**Comment by keisuke-nakata** [comment]
I never think this is the optimal, but setting `some/path/to/pythonwrapper.sh` as `Python Executable Path` and **`$PROJECT_NAME` as `Mypy Path`** worked.
(Because I'm not using `MYPYPATH` right now 🙄 )

`pythonwrapper.sh`:

```
#!/bin/sh

PROJECT_NAME=$MYPYPATH
unset $MYPYPATH
PYENVDIR="/Users/keisuke.nakata/.pyenv/versions/${PROJECT_NAME}"

if [ -d ${PYENVDIR} ]; then
  PYTHONEXECUTABLE=${PYENVDIR}/bin/python
else
  PYTHONEXECUTABLE=python
fi

$PYTHONEXECUTABLE "$@"

exit $?
```

**Comment by elarivie** [comment]
Hello @keisuke-nakata,

I am glad that you now have a solution for your specific use case.

About MYPYPATH, if you ever need it you'll be able to add it directly within the wrapper script just before calling the real python executable.
