### ISSUE TITLE
Are mypy plugins supported ?

### ISSUE THREAD

**Issue by AugPro** [elarivie/linter-mypy#27]
I recently started using pydantic and wanted the extra features brought by the mypy plugin.

Here is what my setup.cfg looks like
```ini
[mypy]
python_version = 3.8
files=**/*.py
plugins = pydantic.mypy

[pydantic-mypy]
init_typed = True
```

In the file `foo.py` I have the following code:
```python
from pydantic import BaseModel

class Foo(BaseModel):
    bar: str

Foo(bar=1)
a: str = 1
```

When running `mypy` in the command line I get the following errors (which are expected):
```bash
foo.py:6: error: Argument "bar" to "Foo" has incompatible type "int"; expected "str"
foo.py:7: error: Incompatible types in assignment (expression has type "int", variable has type "str")
```

However, in Atom, I only get the second error (which indicates the file in indeed watched by linter-mypy), but not the first one (provided by the pydantic-mypy plugin).

Do you have any ideas on how to debug this ?

Thank you !

**Comment by elarivie** [comment]
Hello @AugPro, to debug what is happening behind the scene you can use a python wrapper script

Within the atom package linter-mypy settings
Configure the path to python to a shell script like:

```
#!/bin/sh
# Launch the real python + forward to it every arguments that the wrapper script received
/usr/bin/python3 "$@"

#Exit with the status code of python
exit $?
```

You will then be able to inspect what is happening
 you could add some echo "BlaBla" > ~/DebugStuff.txt
 
 Some of the stuff you may want to inspect are:

- Current working directory being use
- The MYPYPATH environment variable
- The PYTHONPATH environment variable
- The command line arguments provided "$@"

By extracting those information you'll be able to manually call Mypy the same way the linter-mypy package is doing and be able to debug and find what is being done differently/what is missing to get your plugin used

**Comment by AugPro** [comment]
Thank you for your quick response @elarivie. Very nice trick, I didn't think about it. I'll test all that soon

**Comment by AugPro** [comment]
I took some time to debug and found the issue, turns out that the errors were not the same because I thought both commands (from terminal and via linter-mypy) used setup.cfg as it was at the root of my project, and I thought linter-mypy used the file if it existed, but I was wrong ! The solution was simply to explicit the path of setup.cfg in the settings of linter-mypy.

Thanks for the help, we can close this issue

**Comment by elarivie** [comment]
@AugPro,

Glad you found a solution to your issue,

FYI, since you are using setup.cfg... you should try this other atom package: [python-linters](https://atom.io/packages/python-linters)

It loads the settings from the "setup.cfg" and it supports all of those linter: flake8, mypy, pydocstyle, pylint

**Note:** I am the author of both package (linter-mypy and python-linters)

**Comment by AugPro** [comment]
aah very nice! I'll look into that :) Thanks
