### ISSUE TITLE
Running mypy inside project

### ISSUE THREAD

**Issue by dundee** [elarivie/linter-mypy#4]
Please don't run mypy inside project (using cwd). It's not recommended by mypy authors because it does not work correctly - https://github.com/python/mypy/issues/2974

**Comment by elarivie** [comment]
@Dundee, Thanks for the feedback, I didn't knew about this limitation of Mypy.

I just did commit a workaround which at least prevent the ugly crash pop-ups and more cleanly handles the situation.  It now adds a lint error for the file with the error message "Top-level module cannot use a relative import" and it provides a link to the MyPy bug.

Before changing the way linter-mypy calls MyPy I'll need to investigate more about the best way of doing it for a given file versus where should the cwd be set to.

**Comment by dundee** [comment]
Great, thanks!

**Comment by elarivie** [comment]
@Dundee It is now fix and available in linter-mypy v2.1.2

It now runs mypy with cwd set to the file system root folder under which the file being linted is.

- Linux:
  - /x/y/z.py … **cwd =** /
- Windows:
  - c:/x/y/z.py … **cwd =** c:/

I also tested and successfully linted this test case: https://github.com/aquavitae/mypy-test

**Comment by dundee** [comment]
Great, it works, thanks!
