### ISSUE TITLE
Unable to find mypy, despite correct $PATH and settings

### ISSUE THREAD

**Issue by nickpresta** [elarivie/linter-mypy#6]
Hello,

I'm trying to use `linter-mypy` with Python 3 project (python installed with `pyenv`). When I run the linter, I get:

![image](http://d.pr/i/0SpCG.png)

Even though I have `mypy` installed, and the settings for `linter-mypy` are correct, as far as I can tell.

```
$ /Users/npresta/.pyenv/shims/python -m pip install mypy
Requirement already satisfied: mypy in /Users/npresta/.pyenv/versions/3.6.2/lib/python3.6/site-packages
Requirement already satisfied: typed-ast<1.1.0,>=1.0.4 in /Users/npresta/.pyenv/versions/3.6.2/lib/python3.6/site-packages (from mypy)
```

Similarly, my settings are configured as such:

![image](http://d.pr/i/uPvnWC.png)

When I open up the console in Atom, I see:

```
> process.env['PATH']
> "/Users/npresta/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
```

Any ideas? I'm using Atom Beta 1.20.0-beta4

**Comment by elarivie** [comment]
@nickpresta 

Hi Nick,

What is the output of

    /Users/npresta/.pyenv/shims/python -m mypy --version

    /Users/npresta/.pyenv/shims/python -m mypy --help


If you get the error message "No module named mypy" [this is the message which triggers the pop-up when using linter-mypy](https://github.com/elarivie/linter-mypy/blob/bfa257ad07f4d2360d592b7e52e15d9ff0ca005d/lib/init.coffee#L435)

**Comment by elarivie** [comment]
@nickpresta 
Hello Nick,

I am not an expert of pyenv... but when I took a look at their documentation if found the [rehash command](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-rehash) which seems to be what you are looking for.

The description of this command is:

> Installs shims for all Python binaries known to pyenv (i.e., ~/.pyenv/versions/*/bin/*). **Run this command after** you install a new version of Python, or **install a package that provides binaries**.

Indeed, installing mypy does install a new binary (mypy) into the python installation.

So I guess you need to run the following command to complete mypy installation in your environment:

`pyenv rehash`

**Comment by elarivie** [comment]
@nickpresta

This issue is open since 3 months with no new information... I am closing this issue.
