### ISSUE TITLE
$PROJECT_NAME is invalid in case project folder contains dot. 

### ISSUE THREAD

**Issue by rostislav-simonik** [elarivie/linter-mypy#8]
In case that project folder contains dot e.g.
`/path/project.name`

then `$PROJECT_NAME` contains only `project` value instead  of `project.name`.

**Comment by rostislav-simonik** [comment]
Fixed in PR #9

**Comment by elarivie** [comment]
Nice catch, that's a very subtle bug.

**Comment by elarivie** [comment]
This bug is fix with linter-mypy v2.4.1
